services:
  stats-server:
    build: statistics/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=e0gD0os9
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=e0gD0os9

ewm-service:
  build: ewm-service
  container_name: ewm-service-container
  ports:
    - "8080:8080"
  depends_on:
    - ewm-db
  environment:
    - CLIENT_URL=http://stats-server:9090
    - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=e0gD0os9
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

ewm-db:
  image: postgres:16.1
  container_name: ewn-db-container
  ports:
    - "6540:5432"
  environment:
    - POSTGRES_DB=ewm
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=e0gD0os9
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver